spring:
  application:
    name: tenant-separate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    jdbc:
      dialect: postgresql
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

multitenancy:
  http:
    header-name: X-TenantID
  default-schema: public
  strategy: DATABASE
  databases:
    r100_jane:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/r100_jane
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    r100_mike:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/r100_mike
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

